Repository Gjhnsn/QuickR, pull requests merged in 2021-11, with the labels that each got.

#45 Edit folder functionality
  components/folder/FolderContainer/FolderContainer.js
  components/folder/IndividualFolder/IndividualFolder.js
  components/folder/NewFolderModal/NewFolderModal.js
  components/folder/NewFolderModal/styles.js
  redux/folderSlice.js
  redux/modalSlice.js
Labels: enhancement

#46 Folder deletion functionality
  components/AddNewItemMenu/AddNewItemMenu.js
  components/Dashboard/Dashboard.js
  components/folder/FolderActionModal/FolderActionModal.js
  components/folder/FolderActionModal/styles.js
  redux/folderSlice.js
  redux/modalSlice.js
Labels: enhancement

#48 bug(folder-slice): fix delete folder bug
  redux/folderSlice.js
Labels: bug

#50 Delete Alert and Confirm
  App.js
  app.json
  components/AddNewItemMenu/AddNewItemMenu.js
  components/Dashboard/Dashboard.js
  components/Dashboard/styles.js
  components/folder/FolderActionModal/FolderActionModal.js
  components/folder/FolderActionPage/FolderActionPage.js
  components/folder/FolderActionPage/styles.js
  components/folder/FolderContainer/FolderContainer.js
  components/folder/IndividualFolder/IndividualFolder.js
  nav/Navigation.js
  package.json
  redux/modalSlice.js
  utils/toastNote.js
  yarn.lock
Labels: enhancement

#53 Ds 51 folder description and links
  components/AddNewItemMenu/AddNewItemMenu.js
  components/folder/FolderActionPage/FolderActionPage.js
  components/folder/FolderActionPage/styles.js
Labels: enhancement

#54 Ds 52 implement color picker
  components/ColorPicker/ColorPicker.js
  components/ColorPicker/styles.js
  components/folder/FolderActionPage/FolderActionPage.js
  components/folder/FolderActionPage/styles.js
  utils/approvedColors.js
Labels: enhancement

#56 Implement folder picker
  components/UrlModal/UrlModal.js
  components/UrlModal/styles.js
  package.json
  yarn.lock
Labels: enhancement

#57 adding links functionality
  README.md
  components/AddNewItemMenu/AddNewItemMenu.js
  components/Dashboard/Dashboard.js
  components/TopBar/TopBar.js
  components/UrlModal/UrlModal.js
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/AddFolderPage/styles.js
  components/folder/EditFolderPage/EditFolderPage.js
  components/folder/EditFolderPage/styles.js
  components/folder/IndividualFolder/IndividualFolder.js
  nav/Navigation.js
  redux/folderSlice.js
  redux/modalSlice.js
Labels: enhancement

#59 Ds 58 url modal bug
  README.md
  components/UrlModal/UrlModal.js
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/EditFolderPage/EditFolderPage.js
  utils/toastNote.js
Labels: bug, enhancement

#60 Edit link functionality
  README.md
  components/EditUrlModal/EditUrlModal.js
  components/EditUrlModal/styles.js
  components/folder/EditFolderPage/EditFolderPage.js
  redux/folderSlice.js
  redux/modalSlice.js
Labels: enhancement

#62 feat(delete-link): implement delete link functionality, add toast notification
  components/EditUrlModal/EditUrlModal.js
  components/folder/EditFolderPage/EditFolderPage.js
  redux/folderSlice.js
  utils/toastNote.js
Labels: enhancement

#66 Ds 65 refactor scan or add modal
  README.md
  components/AddNewItemMenu/AddNewItemMenu.js
  components/AddOrScanModal/AddOrScanModal.js
  components/AddOrScanModal/styles.js
  components/BarcodeScanner/BarcodeScanner.js
  components/Dashboard/Dashboard.js
  components/EditUrlModal/EditUrlModal.js
  components/EditUrlModal/styles.js
  components/UrlModal/UrlModal.js
  components/UrlModal/styles.js
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/EditFolderPage/EditFolderPage.js
  redux/modalSlice.js
Labels: enhancement

#75 feat(data-persistence): implement redux persist and async storage
  App.js
  package.json
  redux/store.js
  yarn.lock
Labels: enhancement

#78 feat(blobColor): dynamically render blobcolor based on link selected
  assets/quickRLogo.svg
  components/ColorBlob/ColorBlob.js
  components/ColorBlob/styles.js
  components/Svg/svgComponent.js
  components/TopBar/TopBar.js
  components/TopBar/styles.js
  components/folder/IndividualLinks/IndividualLinks.js
  package.json
  redux/folderSlice.js
  utils/approvedColors.js
  yarn.lock
Labels: enhancement

#81 feat(statusbar): implement light mode default for status bar color
  components/Dashboard/Dashboard.js
Labels: enhancement

#82 Pg 71 edit folder page values
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/AddFolderPage/styles.js
  components/folder/EditFolderPage/EditFolderPage.js
  components/folder/EditFolderPage/styles.js
Labels: enhancement

#83 Share feature
  components/EditUrlModal/EditUrlModal.js
  components/QrContainer/QrContainer.js
  components/QrContainer/styles.js
  components/UrlModal/UrlModal.js
Labels: enhancement

#86 Add hitslop to necessary pressable icons
  components/AddNewItemMenu/AddNewItemMenu.js
  components/BarcodeScanner/BarcodeScanner.js
  components/EditUrlModal/EditUrlModal.js
  components/QrContainer/QrContainer.js
  components/TopBar/TopBar.js
  components/UrlModal/UrlModal.js
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/EditFolderPage/EditFolderPage.js
  components/folder/IndividualFolder/IndividualFolder.js
Labels: enhancement

#89 Dynamically render folder icons
  components/folder/IndividualFolder/IndividualFolder.js
  components/folder/IndividualFolder/styles.js
Labels: enhancement

#91 Ds 84 app initial states
  assets/noFolderPlaceholder.svg
  assets/qrPlaceholder.svg
  components/Dashboard/Dashboard.js
  components/Dashboard/styles.js
  components/EditUrlModal/EditUrlModal.js
  components/QrContainer/QrContainer.js
  components/Svg/logoSvgComponent.js
  components/Svg/noFolderSvgPlaceholderComponent.js
  components/Svg/qrSvgPlaceholderComponent.js
  components/TopBar/TopBar.js
  components/folder/EditFolderPage/EditFolderPage.js
  components/folder/FolderContainer/FolderContainer.js
  components/folder/FolderContainer/styles.js
  redux/folderSlice.js
  redux/qrSlice.js
Labels: enhancement

#95 feat(app): hook up buttons to proper functions
  components/folder/EditFolderPage/EditFolderPage.js
  components/folder/FolderContainer/FolderContainer.js
Labels: enhancement

#96 Edit url modal values
  components/EditUrlModal/EditUrlModal.js
  components/EditUrlModal/styles.js
  components/UrlModal/UrlModal.js
  components/UrlModal/styles.js
  components/folder/EditFolderPage/styles.js
Labels: enhancement

#99 bug(folder-color-indicator): render folder color indicator from redux…
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/EditFolderPage/EditFolderPage.js
Labels: bug

#100 Pg 98 font styling and spacing
  App.js
  components/AddNewItemMenu/styles.js
  components/Dashboard/Dashboard.js
  components/QrContainer/QrContainer.js
  components/QrContainer/styles.js
  components/folder/AddFolderPage/styles.js
  components/folder/EditFolderPage/styles.js
  components/folder/FolderContainer/FolderContainer.js
  components/folder/FolderContainer/styles.js
  components/folder/IndividualFolder/styles.js
  components/folder/IndividualLinks/styles.js
  package.json
  yarn-error.log
  yarn.lock
Labels: enhancement

#106 Styling for android and Scan fix
  components/AddNewItemMenu/styles.js
  components/Dashboard/Dashboard.js
  components/Dashboard/styles.js
  components/TopBar/styles.js
  components/UrlModal/UrlModal.js
  components/UrlModal/styles.js
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/AddFolderPage/styles.js
  components/folder/EditFolderPage/EditFolderPage.js
  components/folder/EditFolderPage/styles.js
  components/folder/IndividualFolder/IndividualFolder.js
  components/folder/LinksContainer/LinksContainer.js
  utils/toastNote.js
Labels: bug

#108 Adding link validation
  components/AddNewItemMenu/AddNewItemMenu.js
  components/BarcodeScanner/BarcodeScanner.js
  components/EditUrlModal/EditUrlModal.js
  components/UrlModal/UrlModal.js
  components/folder/EditFolderPage/EditFolderPage.js
  package.json
  utils/toastNote.js
  yarn.lock
Labels: bug

#112 feat(disable-description): disable description validation for folders…
  components/EditUrlModal/EditUrlModal.js
  components/UrlModal/UrlModal.js
  components/folder/AddFolderPage/AddFolderPage.js
  components/folder/EditFolderPage/EditFolderPage.js
Labels: enhancement

#117 android picker
  components/UrlModal/UrlModal.js
  components/UrlModal/styles.js
Labels: bug
